repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0839f92796ae388643a08a21640a029b322be5c2  # frozen: v0.15.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=500]
